### ISSUE TITLE
typescript-react-intl doesn't work with TypeScript 2.3.4

### ISSUE THREAD

**Issue by mihai-dinculescu** [bang88/typescript-react-intl#7]
```
$ npm test

> typescript-react-intl@0.1.6 test C:\Users\mihai.dinculescu\Desktop\typescript-react-intl
> ava --verbose


  × <FormattedMessage/> Error: element.attributes.forEach is not a function
  √ defineMessages() should only work with variable declaration
  × <FormattedMessage/> should work with StatelessComponent Error: element.attributes.forEach is not a function
  √ It should return empty Array when not found

  2 tests failed [15:25:20]


  1. <FormattedMessage/>
  TypeError: element.attributes.forEach is not a function
    index.ts:90:28
    main (index.ts:88:24)
    Test.t [as fn] (test/index.js:10:13)


  2. <FormattedMessage/> should work with StatelessComponent
  TypeError: element.attributes.forEach is not a function
    index.ts:90:28
    main (index.ts:88:24)
    Test.t [as fn] (test/index.js:60:13)

```

**Comment by mihai-dinculescu** [comment]
@bang88, Thank you very much for the prompt fix!

**Comment by BANG88** [comment]
You are welcome. 😃
